name: CMake

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'aosc/aosc-os-buildkit:latest'
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      shell: bash
      run: |
        apt-get update
        apt-get install -y cmake ninja pandoc
    - name: Query tag name
      uses: little-core-labs/get-git-tag@v3.0.2
    - name: Build
      shell: bash
      run: ./.ci/build.sh
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          build/*.tar*
          build/*.deb
          build/*.sha256


  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/download-artifact@v2
      - name: Query tag name
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagName.outputs.tag }}
          release_name: ${{ steps.tagName.outputs.tag }}
          draft: false
          prerelease: false
      - name: Upload artifacts
        uses: alexellis/upload-assets@0.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./**/*.tar.xz","./**/*.deb", "./**/*.sha256"]'
